"""V0_2_0_packages_updated

Revision ID: 82fe34697525
Revises: 7b2d42db07d1
Create Date: 2026-06-16 17:24:44.296089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82fe34697525'
down_revision: Union[str, Sequence[str], None] = '7b2d42db07d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('packages', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'updated_at')
    op.drop_column('packages', 'created_at')
    # ### end Alembic commands ###
