"""V0.0.5 upgrade models names with default

Revision ID: 91efe119c722
Revises: 23134dcf48eb
Create Date: 2026-06-09 19:17:37.660433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91efe119c722'
down_revision: Union[str, Sequence[str], None] = '23134dcf48eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category_name', sa.String(), nullable=False))
    op.drop_column('categories', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('categories', 'category_name')
    # ### end Alembic commands ###
